# Generated by Django 3.0.3 on 2020-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zila_app', '0002_auto_20200606_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(choices=[('d', 'Delivered'), ('p', 'Placed'), ('s', 'Shipped'), ('r', 'Return')], default='IDLE', max_length=1),
            preserve_default=False,
        ),
    ]
